apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodevsuapi
  namespace: applications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demodevsuapi
  template:
    metadata:
      labels:
        app: demodevsuapi
    spec:
      containers:
        - name: app
          image: public.ecr.aws/g0d0u9h2/demodevsuapi:latest #Image from repository ECR 
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
